### ISSUE TITLE
all buttons act as a submit button for login form on login page

### ISSUE THREAD

**Issue by tomki1** [notkimroberts/collectors-trading-platform#33]

**Comment by jhhlim** [comment]
that's a strange issue but my guess would be that there is a routing or redirect issue. Maybe we have to check on the names for all the buttons? (including nav.hbs)

**Comment by jhhlim** [comment]
My guess would be for the LOGIN BUTTON to only fire when:

function submit() { $(() => {

    $('form').submit((event) => {
        event.preventDefault();
        const collector = getUserFromForm();


        login(collector)
            .then(result => {
               setIdRedirect(result);
            }).catch(err => {
                console.error(err);
                showErrorMessage(err.responseJSON.message);                
            });
    });
});
}

Currently it is firing anytime form recognizes a "submit button" being pressed. I am seeing in nav.hbs that register, search collectible, search collector are all submit buttons. So you are able to navigate to other pages which are not submit buttons from login.hbs such as home, collectibles all tab, etc.

**Comment by jhhlim** [comment]
I tried adding this to the login.hbs but it didn't work for logging in, however it does allow me to navigate to the register tab 

            <button class="btn btn-primary" onclick=submit() name="login" type="submit">Login</button>
